services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    # REMOVER: ports: - "80:80"

  proxy:
    build:
      context: ./server  
      dockerfile: Dockerfile
    restart: always
    # REMOVER: ports: - "3000:3000"